
server:  port: 9010
spring:
  kafka:

    producer:
      bootstrap-servers: 0.0.0.0:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: com.test.pca.serializers.JsonPOJOSerializer
      properties:
        spring:
          json:
            trusted:
              packages: com.test.pca.entities
    listener:      missing-topics-fatal: false